timeout = 80
timeout_incomplete = 500
prevent_wake = 1
secret = "/vy9NC43UqyUL2pynLWQKQ"
# logfile = "C:\\Users\\mackb\\AppData\\Roaming\\talon\\draconity.log"

[[socket]]
host = "127.0.0.1"
port = 38065

# [[socket]]
# host = "127.0.0.1"
# port = 38065

# [[remote]]
# host = "127.0.0.1"
# port = 38065
